# Gamut Mapping - RGB & HSV Gamut Mapping Study Models Fitting

In [1]:
%matplotlib widget

In [2]:
from __future__ import division, unicode_literals

import colour
import matplotlib.pyplot as plt
import numpy as np
import os
import scipy.interpolate
import scipy.optimize
from functools import reduce

COLOUR_STYLE = colour.plotting.colour_style()
COLOUR_STYLE.update({
    'figure.figsize': (10.24, 5.12),
    'legend.framealpha':
    colour.plotting.COLOUR_STYLE_CONSTANTS.opacity.low
})

plt.style.use(COLOUR_STYLE)

plt.style.use('dark_background')

colour.utilities.describe_environment()

colour.utilities.filter_warnings(*[True] * 4);

*                                                                             *
*   Interpreter :                                                             *
*       python : 3.7.6 (default, Dec 30 2019, 19:38:26)                       *
*                [Clang 11.0.0 (clang-1100.0.33.16)]                          *
*                                                                             *
*   colour-science.org :                                                      *
*       colour : v0.3.15-141-g3bebd7e9                                        *
*                                                                             *
*   Runtime :                                                                 *
*       imageio : 2.8.0                                                       *
*       matplotlib : 3.0.3                                                    *
*       numpy : 1.18.4                                                        *
*       scipy : 1.4.1                   

## Colour Wheel & Colour Stripe Generation

In [3]:
def colour_stripe(S=1, samples=360):
    H = np.linspace(0, 1, samples)

    HSV = colour.utilities.tstack([H, np.ones(samples) * S, np.ones(samples)])
    RGB = colour.HSV_to_RGB(HSV)
 
    return RGB[np.newaxis, ...]


def colour_wheel(samples=1024, clip_circle=True, method='Colour'):
    xx, yy = np.meshgrid(
        np.linspace(-1, 1, samples), np.linspace(-1, 1, samples))

    S = np.sqrt(xx ** 2 + yy ** 2)    
    H = (np.arctan2(xx, yy) + np.pi) / (np.pi * 2)

    HSV = colour.utilities.tstack([H, S, np.ones(H.shape)])
    RGB = colour.HSV_to_RGB(HSV)

    if clip_circle == True:
        RGB[S > 1] = 0
        A = np.where(S > 1, 0, 1)
    else:
        A = np.ones(S.shape)

    if method.lower()== 'matplotlib':
        RGB = colour.utilities.orient(RGB, '90 CW')
    elif method.lower()== 'nuke':
        RGB = colour.utilities.orient(RGB, 'Flip')
        RGB = colour.utilities.orient(RGB, '90 CW')

    R, G, B = colour.utilities.tsplit(RGB)
    
    return colour.utilities.tstack([R, G, B, A])

In [4]:
COLOUR_STRIPE = colour_stripe();

COLOUR_WHEEL = colour_wheel(360, clip_circle=False)[..., 0:3]

colour.plotting.plot_image(np.resize(COLOUR_STRIPE, [36, 360, 3]));

with plt.style.context({'figure.figsize': (10.24, 10.24)}):

    colour.plotting.plot_image(COLOUR_WHEEL);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Compression Function

In [5]:
def tanh_compression_function(x, a=0.8, b=1 - 0.8):
    x = colour.utilities.as_float_array(x)

    return np.where(x > a, a + b * np.tanh((x - a) / b), x)

## Gamut Mapping Study Models Difference

In [6]:
SAMPLES = np.linspace(0, 1, 360)
THRESHOLDS = [0, 0.5, 0.9]


def hue_offset(x, a, b, c):
    return np.sin(x * a + b) * c


def medicina_HSV_control(
        a=(np.pi * 6, np.pi, np.pi / 180),
        RGB=COLOUR_STRIPE,
        S_c=0,
        C_f=tanh_compression_function):
    H, S, V = colour.utilities.tsplit(colour.RGB_to_HSV(RGB))

    HSV = colour.utilities.tstack([(H + hue_offset(SAMPLES, *a)) % 1,
                                   C_f(S, S_c, 1 - S_c), V])

    return colour.HSV_to_RGB(HSV)


def medicina_RGB_saturation(RGB=COLOUR_STRIPE,
                            C_t=0,
                            C_f=tanh_compression_function):
    L = np.max(RGB, axis=-1)[..., np.newaxis]

    D = np.abs(RGB - L) / L

    D_c = C_f(D, C_t, 1 - C_t)

    RGB_c = L - D_c * L

    return RGB_c


RGB_S = medicina_RGB_saturation()

In [7]:
colour.plotting.plot_image(np.resize(medicina_HSV_control(), [36, 360, 3]));

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [8]:
colour.plotting.plot_image(np.resize(RGB_S, [36, 360, 3]));

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [9]:
colour.plotting.plot_image(
    np.resize(
        np.abs(medicina_HSV_control([0, 0, 0]) - RGB_S) * 5, [36, 360, 3]));

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Optimisation & Curve Fitting

After some initial tests, it seemed like the closest function to minimize the error was a triangle or sine wave: https://community.acescentral.com/t/gamut-mapping-in-cylindrical-and-conic-spaces/2870/10?u=thomas_mansencal

$\sin\bigg(x \cdot \pi \cdot 6 + \pi\bigg) * \cfrac{\pi}{\approx180}$

is almost the best fitting function for the maximum saturation case, the rounded 180 value just happens to be convenient here but the actual value is slightly lower.

In [10]:
SATURATION_SAMPLES = np.linspace(0, 8, 200)
STRIPES = np.vstack([colour_stripe(a) for a in SATURATION_SAMPLES])

PARAMETERS = []
for threshold in THRESHOLDS:
    i = 0

    def objective_function(abc):
        stripe = STRIPES[i]
        return np.sum(
            np.abs(
                medicina_HSV_control(abc, stripe, S_c=threshold) -
                medicina_RGB_saturation(stripe, C_t=threshold)))

    parameters = []
    for i in range(len(STRIPES)):
        parameters.append(
            scipy.optimize.minimize(objective_function,
                                    (np.pi * 6, np.pi, np.pi / 180)))

    PARAMETERS.append(parameters)

In [11]:
for parameters in PARAMETERS:
    with plt.style.context({'figure.figsize': (10.24, 10.24)}):
        colour.plotting.artist()

        for parameter in parameters[1::5]:
            plt.plot(
                SAMPLES,
                np.sin(
                    np.linspace(0, 1, len(SAMPLES)) * parameter.x[0] +
                    parameter.x[1]) * parameter.x[2])

        for i in np.arange(0, 360 + 60, 60) / 360:
            plt.axvline(i, c='r')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [12]:
with plt.style.context({'figure.figsize': (10.24, 10.24)}):
    colour.plotting.artist()

    for parameters in PARAMETERS:
            plt.plot(SATURATION_SAMPLES, [parameter.x[0] for parameter in parameters])

with plt.style.context({'figure.figsize': (10.24, 10.24)}):
    colour.plotting.artist()

    for parameters in PARAMETERS:
            plt.plot(SATURATION_SAMPLES, [parameter.x[1] for parameter in parameters])

with plt.style.context({'figure.figsize': (10.24, 10.24)}):
    colour.plotting.artist()

    for parameters in PARAMETERS:
            plt.plot(SATURATION_SAMPLES, [parameter.x[2] for parameter in parameters])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [13]:
def curve_segment(x, m_lnA, m_B, m_offsetX, m_offsetY, m_scaleX=1, m_scaleY=1):
    x0 = (x - m_offsetX) * m_scaleX
    y0 = np.exp(m_lnA + m_B * np.log(x0))

    return np.where(x > 0, y0 * m_scaleY + m_offsetY, 0)


def solve_A_B(x0, y0, m):
    B = (m * x0) / y0
    lnA = np.log(y0) - B * np.log(x0)

    return lnA, B


def as_slope_intercept(x0, x1, y0, y1):
    dx = (x1 - x0)
    dy = (y1 - y0)

    m = 1 if dx == 0 else dy / dx
    b = y0 - x0 * m

    return m, b


def eval_derivative_linear_gamma(m, b, g, x):
    return g * m * np.power(m * x + b, g - 1.0)


def curve(x, g, m_x0, m_y0, m_x1, m_y1, m_overshoot_x, m_overshoot_y):
    m_x1 = max(m_x0, m_x1)
    m_y1 = max(m_y0, m_y1)

    m_overshoot_x = max(m_x1 - 1, m_overshoot_x)
    m_overshoot_y = max(m_y1 - 1, m_overshoot_y)

    m, b = as_slope_intercept(m_x0, m_x1, m_y0, m_y1)

    linear_segment = curve_segment(x, g * np.log(m), g, -(b / m), 0)

    toe_M = eval_derivative_linear_gamma(m, b, g, m_x0)
    shoulder_M = eval_derivative_linear_gamma(m, b, g, m_x1)

    m_y0 = np.power(m_y0, g)
    m_y1 = np.power(m_y1, g)
    m_overshoot_y = np.power(1 + m_overshoot_y, g) - 1

    A_t, B_t = solve_A_B(m_x0, m_y0, toe_M)
    toe_segment = curve_segment(x, A_t, B_t, 0, 0)

    x0 = (1 + m_overshoot_x) - m_x1
    y0 = (1 + m_overshoot_y) - m_y1
    A_s, B_s = solve_A_B(x0, y0, shoulder_M)
    shoulder_segment = curve_segment(x, A_s, B_s, 1 + m_overshoot_x,
                                     1 + m_overshoot_y, -1, -1)

    y = np.select(
        [
            x < m_x0,
            np.logical_and(x > m_x0, x < m_x1),
            np.logical_and(x > m_x1, x < m_overshoot_x + 1),
            x > m_overshoot_x + 1,
        ],
        [
            toe_segment, linear_segment, shoulder_segment,
            np.nanmax(shoulder_segment, )
        ],
    )

    return y

In [14]:
POPTS = []
for parameters in PARAMETERS:
    offset_r = [parameter.x[2] for parameter in parameters]

    offset_r[0] = 0

    popt, pcov = scipy.optimize.curve_fit(
        curve,
        SATURATION_SAMPLES,
        offset_r,
        bounds=np.transpose([
            (.75, 1.25),
            (0, 1.5),
            (0.005, 0.01),
            (0, 2.5),
            (0.01, 0.2),
            (1, 8),
            (-1, -0.7),
        ]),
        maxfev=50000)
    
    POPTS.append(popt)
    print(popt)
    print(
        colour.utilities.metric_mse(offset_r, curve(SATURATION_SAMPLES,
                                                    *popt)))

    with plt.style.context({'figure.figsize': (10.24, 10.24)}):
        colour.plotting.artist()

        plt.plot(SATURATION_SAMPLES, offset_r)
        plt.plot(SATURATION_SAMPLES, curve(SATURATION_SAMPLES, *popt), 'o')

[ 1.25        0.41828126  0.01        1.56583187  0.06968826  8.
 -0.86023655]
1.24955653779e-07


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[ 1.01979549  0.95474635  0.01        1.47723114  0.04121946  5.43908318
 -0.91030243]
3.49777070594e-07


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[ 1.22100573  0.99352605  0.00541947  1.22818909  0.04039225  3.14674915
 -0.86669221]
5.63774296283e-07


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [15]:
print(np.transpose(POPTS))

with plt.style.context({'figure.figsize': (10.24, 10.24)}):
    colour.plotting.artist()
    for popt in POPTS:
        plt.plot(SATURATION_SAMPLES, curve(SATURATION_SAMPLES, *popt))

[[  1.25000000e+00   1.01979549e+00   1.22100573e+00]
 [  4.18281263e-01   9.54746350e-01   9.93526049e-01]
 [  1.00000000e-02   1.00000000e-02   5.41946590e-03]
 [  1.56583187e+00   1.47723114e+00   1.22818909e+00]
 [  6.96882649e-02   4.12194631e-02   4.03922518e-02]
 [  8.00000000e+00   5.43908318e+00   3.14674915e+00]
 [ -8.60236546e-01  -9.10302426e-01  -8.66692207e-01]]


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [16]:
def hue_offset_extended(x, S, g, m_x0, m_y0, m_x1, m_y1, m_overshoot_x, m_overshoot_y):
    return np.sin(x * np.pi * 6 + np.pi) * curve(S, g, m_x0, m_y0, m_x1, m_y1, m_overshoot_x, m_overshoot_y)


def medicina_HSV_control_extended(a=POPTS[0],
                                  RGB=COLOUR_STRIPE,
                                  S_c=0,
                                  C_f=tanh_compression_function):
    H, S, V = colour.utilities.tsplit(colour.RGB_to_HSV(RGB))

    HSV = colour.utilities.tstack(
        [(H + hue_offset_extended(H, S, *a)) % 1,
          C_f(S, S_c, 1 - S_c), V])

    return colour.HSV_to_RGB(HSV)


with plt.style.context({'figure.figsize': (10.24, 10.24)}):
#     colour.plotting.plot_image(STRIPES);

    colour.plotting.plot_image(
            np.abs(
                medicina_HSV_control([0, 0, 0], RGB=STRIPES) -
                medicina_RGB_saturation(STRIPES)) * 5);

    colour.plotting.plot_image(
            np.abs(
                medicina_HSV_control_extended(RGB=STRIPES) -
                medicina_RGB_saturation(STRIPES)) * 5);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [17]:
with plt.style.context({'figure.figsize': (10.24, 10.24)}):
    colour.plotting.plot_image(
        np.abs(
            medicina_HSV_control([0, 0, 0], RGB=COLOUR_WHEEL) -
            medicina_RGB_saturation(COLOUR_WHEEL)) * 5)

    colour.plotting.plot_image(
        np.abs(
            medicina_HSV_control_extended(RGB=COLOUR_WHEEL) -
            medicina_RGB_saturation(COLOUR_WHEEL)) * 5)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …